services:
  app:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
    environment:
      - GEMINI_AI_API_KEY=${GEMINI_AI_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
