services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - GEMINI_AI_API_KEY=${GEMINI_AI_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
